import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import './globals.css'
import Navbar from './components/layout/Navbar'
import Footer from './components/layout/Footer'
import Providers from './provider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
import 'swiper/swiper-bundle.css'

const prompt = Prompt({ subsets: ['latin', 'thai'], weight : ['100', '200', '300', '400', '500', '600', '700', '800', '900']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={prompt.className+" text-gray-900"}>
        <Providers>
          <Navbar />
          {children}
          <ToastContainer />
          <Footer />
        </Providers>
      </body>

    </html>
  )
}
